DROP TABLE IF EXISTS `SOLDIERS`;

CREATE TABLE `SOLDIERS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `COMBAT_POWER` int NOT NULL,
  `STRENGTH_SOLDIER_MEETING` int NOT NULL,
  `STRENGTH_DISTANCE_SOLDIERS` int NOT NULL,
  `LOOTING_CAPACITY` int NOT NULL,
  `TRAVEL_VELOCITY` int NOT NULL,
  `FOOD` int NOT NULL,
  `TYPE` varchar(4) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

COMMIT;